  fc_fagtb:
  input:
    train: "train.csv"
    test: "test.csv"
  output:
    pred: "pred.csv"
    test: "test.csv"
    log: "log.csv"
    result: "result.csv"
  format:
    sep: ","  
  parameters:
    label_col: "two_year_recid" #"income-per-year"
    sens: "race" #"sex"
    columns_delete: "sex-race" #"race-sex"
    test_size: 0.2
    n_estimators: 100
    learning_rate: 0.01
    random_state: 42
    metric: "matth" # accuracy, roc_auc or matthews_correlation_coefficient. For multi-label this should be accuracy        
  algo:
    max_iterations: 10      
  split:
    mode: "file" # directory if cross validation was used before, else file
    dir: "." # data if cross validation app was used before, else .              
